"""empty message

Revision ID: 824ca3d4d1b0
Revises: 893f916efa7d
Create Date: 2023-09-26 15:23:08.716230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '824ca3d4d1b0'
down_revision: Union[str, None] = '893f916efa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logins', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('logins', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_logins_id'), 'logins', ['id'], unique=False)
    op.create_index(op.f('ix_logins_username'), 'logins', ['username'], unique=True)
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_logins_username'), table_name='logins')
    op.drop_index(op.f('ix_logins_id'), table_name='logins')
    op.alter_column('logins', 'password',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('logins', 'username',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
