"""empty message

Revision ID: 893f916efa7d
Revises: 6368c34c204c
Create Date: 2023-09-19 10:08:28.513681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '893f916efa7d'
down_revision: Union[str, None] = '6368c34c204c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filedata', sa.Column('filetype', sa.String(length=50), nullable=True))
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.drop_column('filedata', 'filetype')
    # ### end Alembic commands ###
